# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main

resources:
  - repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          # Step 1: Checkout the source code
          - checkout: self

          # Step 2: Install Java 17 (OpenJDK)
          - script: |
              sudo apt-get update
              sudo apt-get install -y openjdk-17-jdk
              echo "##vso[task.setvariable variable=JAVA_HOME]$(readlink -f /usr/bin/java | sed "s:/bin/java::")"
              export JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:/bin/java::")
              echo "JAVA_HOME is set to $JAVA_HOME"
              java -version
              javac -version
            displayName: 'Install and Set OpenJDK 17'

          - script: |
              echo "Setting JAVA_HOME for Maven"
              echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
              export PATH=$JAVA_HOME/bin:$PATH
              mvn -version
            displayName: 'Set JAVA_HOME for Maven'
          
          - script: |
              java -version
              mvn -version
            displayName: 'Verify Java and Maven Versions'

          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'clean install'
              options: '-DskipTests=true'  # Skip tests if not needed
              publishJUnitResults: true
              testResultsFiles: '**/TEST-*.xml'
              mavenVersionOption: 'Default'

          # Step 5: Build and push the Docker image
          - task: Docker@2
            inputs:
              containerRegistry: 'docker'  # Update with your Docker registry service connection name
              repository: 'sharmanayan/Synergy_Test'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: |
                $(tag)






    # - task: Docker@2
    #   displayName: Build an image
    #   inputs:
    #     command: build
    #     dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    #     tags: |
    #       $(tag)
