# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main

resources:
  - repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          # Step 1: Checkout the source code
          - checkout: self

          # Step 2: Install Java (OpenJDK 8)
          - script: |
              sudo apt-get update
              sudo apt-get install -y openjdk-8-jdk
              java -version
            displayName: 'Install OpenJDK 8'

          # Step 3: Build the application (Maven example, adjust if using Gradle)
          - script: |
              mvn clean package
            displayName: 'Build Java Application'

          # Step 4: Build and push the Docker image
          - task: Docker@2
            inputs:
              containerRegistry: 'docker'  # Update with your Docker registry service connection name
              repository: 'sharmanayan/Synergy_Test'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: |
                $(tag)



    # - task: Docker@2
    #   displayName: Build an image
    #   inputs:
    #     command: build
    #     dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    #     tags: |
    #       $(tag)
