name: Project CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Assign Date
      run:
        BRANCH=$(echo "$GITHUB_REF" | awk -F'/' '{print $3}')
        echo "BRANCH=$(echo "$GITHUB_REF" | awk -F'/' '{print $3}')" >> $GITHUB_ENV && echo "DATE=$(date +'%d-%m-%Y')" >> $GITHUB_ENV

    - name: Checking
      run:
        echo $BRANCH 
        echo $DATE

    - name: Checking final variable
      run:
        echo $image_new

    - name: Build with Maven
      run: mvn clean install

    - name: Debugging
      id: check-tag
      run: |
        IMAGE_NAME="sharmanayan/springboot-images-new"
        TAG_WITHOUT_BUILD_NUMBER="${{ env.BRANCH }}-${{ env.DATE }}" 
        API_URL="https://hub.docker.com/v2/repositories/$IMAGE_NAME/tags/?page_size=10&ordering=last_updated"
        AUTH_HEADER="Authorization: Bearer ${{ secrets.DOCKER_TOKEN }}"
        RESPONSE=$(curl --location --header "$AUTH_HEADER" "$API_URL")
        LATEST_TAG=$(echo "$RESPONSE" | jq -r ".results[].name | select(. | test(\"$TAG_WITHOUT_BUILD_NUMBER\"))" | sort -rV | head -n 1)
        echo $LATEST_TAG

    - name: Set Latest Tag
      id: set-latest-tag
      run: |
        if [[ "$LATEST_TAG" == "null" ]]; then
          LATEST_TAG="$image_name:$TAG_WITHOUT_BUILD_NUMBER.1"
        else
          numeric_part="${LATEST_TAG##*.}"
          numeric_part=$((numeric_part '+' 1))
          LATEST_TAG="${TAG_WITHOUT_BUILD_NUMBER}.${numeric_part}"
        fi
        echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

    - name: Check Set Tag
      run: |
        echo $LATEST_TAG

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}


    - name: Build & Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: Dockerfile
        push: true
        tags: ${{ env.LATEST_TAG }}
