name: Project cicd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install

    - name: Assign Date
      run:
        echo "BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
        echo "Date= $(date + '%d+%m+%y')" >> $GITHUB_ENV

    - name: Assigning final variable
      run:
        echo "$image_new=$BRANCH-$DATE.1"

    - name: Build & Push docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: sharmanayan/springboot-images-new
        tags: $image_new
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

