name: Project cicd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install

    - name: Assign Date
      run:
        echo "BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
        echo "Date=$(env.DATE)" >> $GITHUB_ENV

    - name: Check Date & Branch % variable
      run:
        echo $BRANCH
        echo $Date
        echo "$image_new=$BRANCH-$DATE.1" >> $GITHUB_ENV

    - name: Checking final variable
      run:
        echo $image_new


