name: Project CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Assign Date
      run:
        BRANCH=$(echo "$GITHUB_REF" | awk -F'/' '{print $3}')
        echo "BRANCH=$(echo "$GITHUB_REF" | awk -F'/' '{print $3}')" >> $GITHUB_ENV && echo "DATE=$(date +'%d-%m-%Y')" >> $GITHUB_ENV

    - name: Checking
      run:
        echo $BRANCH 
        echo $DATE

    - name: Assign Variable
      run:
        echo "image_new=$BRANCH-$DATE.1" >> $GITHUB_ENV

    - name: Checking final variable
      run:
        echo $image_new

    - name: Build with Maven
      run: mvn clean install

    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push Docker Image
      uses: docker/build-push-action@v5
      with:
          image: sharmanayan/springboot-images-new
          tags: $image_new
          registry: docker.io
          dockerfile: Dockerfile

